// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL7pkZc73Q8DglPKtw-2OzM2Cj9GgLwwY',
    appId: '1:900885010704:web:d8a0196366f9d6fd202d95',
    messagingSenderId: '900885010704',
    projectId: 'carenet-69dcf',
    authDomain: 'carenet-69dcf.firebaseapp.com',
    storageBucket: 'carenet-69dcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34YqE-1h46tdTqvOf1nWy2Ok0zWokDqs',
    appId: '1:900885010704:android:002c75a0341bd7b3202d95',
    messagingSenderId: '900885010704',
    projectId: 'carenet-69dcf',
    storageBucket: 'carenet-69dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5fvmnD_HAL3DfthyOpaPh1C-pqzfCKuI',
    appId: '1:900885010704:ios:db2521229613ad25202d95',
    messagingSenderId: '900885010704',
    projectId: 'carenet-69dcf',
    storageBucket: 'carenet-69dcf.firebasestorage.app',
    iosBundleId: 'com.carenet.carenet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5fvmnD_HAL3DfthyOpaPh1C-pqzfCKuI',
    appId: '1:900885010704:ios:db2521229613ad25202d95',
    messagingSenderId: '900885010704',
    projectId: 'carenet-69dcf',
    storageBucket: 'carenet-69dcf.firebasestorage.app',
    iosBundleId: 'com.carenet.carenet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL7pkZc73Q8DglPKtw-2OzM2Cj9GgLwwY',
    appId: '1:900885010704:web:7058822af4cfea94202d95',
    messagingSenderId: '900885010704',
    projectId: 'carenet-69dcf',
    authDomain: 'carenet-69dcf.firebaseapp.com',
    storageBucket: 'carenet-69dcf.firebasestorage.app',
  );
}
