name: carenet
description: "Application de consultation en ligne."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  go_router: ^14.1.0
  file_picker: ^10.2.0
  emoji_picker_flutter: ^4.3.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/Google.png
    - assets/MTN.jpg
    - assets/Orange.png
    - assets/default_profile.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

